/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Pesma;
import java.awt.Frame;
import java.awt.Scrollbar;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javazoom.jl.decoder.JavaLayerException;
import kontroler.Kontroler;
import niti.NitPesma;

/**
 *
 * @author nevenac
 */
public class PesmaGUI extends javax.swing.JDialog {

    /**
     * Creates new form PesmaGUI
     */
    Pesma pesma;
    FileInputStream fis;
    List<Pesma> svePesme;
    
    public PesmaGUI(java.awt.Frame parent, boolean modal, Pesma p, List<Pesma> svePesme) {
        super(parent, modal);
        initComponents();
        this.pesma = p;
        this.svePesme = svePesme;
        postaviStranu();
        Kontroler.getInstance().setDialog(this);
        try {
            fis = new FileInputStream(p.getLokacija());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PesmaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblNazivPesme = new javax.swing.JLabel();
        jbtnPlay = new javax.swing.JButton();
        jbtnStop = new javax.swing.JButton();
        jbtnNext = new javax.swing.JButton();
        jbtnPrevious = new javax.swing.JButton();
        skroler = new java.awt.Scrollbar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlblNazivPesme.setText("jLabel1");

        jbtnPlay.setText("Play");
        jbtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlayActionPerformed(evt);
            }
        });

        jbtnStop.setText("Stop");
        jbtnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStopActionPerformed(evt);
            }
        });

        jbtnNext.setText("Next");
        jbtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNextActionPerformed(evt);
            }
        });

        jbtnPrevious.setText("Previous");
        jbtnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPreviousActionPerformed(evt);
            }
        });

        skroler.setOrientation(java.awt.Scrollbar.HORIZONTAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnPrevious)
                        .addGap(136, 136, 136)
                        .addComponent(jbtnNext))
                    .addComponent(jlblNazivPesme))
                .addGap(0, 77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnPlay, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbtnStop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                        .addComponent(skroler, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jlblNazivPesme)
                .addGap(82, 82, 82)
                .addComponent(jbtnPlay)
                .addGap(28, 28, 28)
                .addComponent(jbtnStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(skroler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnNext)
                    .addComponent(jbtnPrevious))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlayActionPerformed
        jbtnStop.setEnabled(true);
        jbtnPlay.setEnabled(false);
        Kontroler.getInstance().pokreniPesmu(pesma);
    }//GEN-LAST:event_jbtnPlayActionPerformed

    private void jbtnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStopActionPerformed
        jbtnPlay.setEnabled(true);
        jbtnStop.setEnabled(false);
        Kontroler.getInstance().zaustaviPesmu();
    }//GEN-LAST:event_jbtnStopActionPerformed

    private void jbtnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPreviousActionPerformed
        Kontroler.getInstance().zaustaviPesmu();
        Kontroler.getInstance().zatvoriDialog();
        int red = svePesme.indexOf(pesma);
        if (red == 0) {
            red = svePesme.size();
        }
        PesmaGUI pgui = new PesmaGUI((Frame) this.getParent(), true, svePesme.get(red-1), svePesme);
        pgui.setVisible(true);      
    }//GEN-LAST:event_jbtnPreviousActionPerformed

    private void jbtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNextActionPerformed
        Kontroler.getInstance().zaustaviPesmu();
        Kontroler.getInstance().zatvoriDialog();
        int red = svePesme.indexOf(pesma);
        if (red == svePesme.size()-1) {
            red = -1;
        }
        if (red == svePesme.size()-1) {
            red = -1;
        }
        
        PesmaGUI pgui = new PesmaGUI((Frame) this.getParent(), true, svePesme.get(red+1), svePesme);
        pgui.setVisible(true);
       // this.setVisible(false);        
    }//GEN-LAST:event_jbtnNextActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnNext;
    private javax.swing.JButton jbtnPlay;
    private javax.swing.JButton jbtnPrevious;
    private javax.swing.JButton jbtnStop;
    private javax.swing.JLabel jlblNazivPesme;
    private java.awt.Scrollbar skroler;
    // End of variables declaration//GEN-END:variables

    private void postaviStranu() {
        jlblNazivPesme.setText(pesma.getNaziv());
        jbtnPlay.setEnabled(true);
        jbtnStop.setEnabled(false);
    }
}
